apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.service.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  ports:
  - name: {{ .Values.service.name }}
    nodePort: {{ .Values.service.nodePort }}
    port: {{ .Values.service.port }}
    protocol: TCP
  selector:
    app: {{ template "fullname" . }}
  type: "{{ .Values.service.type }}"
  externalTrafficPolicy: Local
